### ISSUE TITLE
Could you provide the python code for parsing "chebi.obo" or "chebi.owl"?

### ISSUE THREAD

**Issue by gaozhangyang** [MGlauer/cheleary#1]

**Comment by MGlauer** [comment]
We used the tool [chebiutils](https://github.com/jannahastings/chebiutils) and more specifically the [learnhelper.py](https://github.com/jannahastings/chebiutils/blob/022c2e0bff6a993a02cdf3b283e282429c1e4738/chebidblite/learnhelper.py#L30) script. More details of how this selection process works, can be found in our [publication](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-021-00500-8).

**Comment by gaozhangyang** [comment]
Thanks for your help!
